server:
  port: 8081

spring:
  application:
    name: catalog-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

threshold-service:
  base-url: http://localhost:8087


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace