server:
  port: 8081

spring:
  application:
    name: catalog-service
  kafka:
    bootstrap-servers: 100.113.120.124:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
  datasource:
    url: jdbc:postgresql://100.113.120.124:5432/catalog_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

threshold-service:
  base-url: http://100.113.120.124:8087

merdeleine:
  kafka:
    topics:
      sell-window-quota-configured: sell-window.quota.configured.v1
      sell-window-closed: sell-window.closed.v1


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace