server:
  port: 8084

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: 100.113.120.124:9092
    listener:
      ack-mode: manual_immediate
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # 這樣就會在 Kafka 消息頭中添加類型信息，方便消費者反序列化
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.use.type.headers: true # 這樣就會使用 Kafka 消息頭中的類型信息來反序列化，而不是全局默認類型

  datasource:
    url: jdbc:postgresql://100.113.120.124:5432/payment_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

app:
  kafka:
    consumer:
      group-id: payment-service-group
    topic:
      payment-requested-events: payment.requested.v1
      payment-created-events: payment.created.v1
      payment-completed-events: payment.completed.v1
      payment-failed-events: payment.failed.v1
  outbox:
    publish-interval-ms: 5000

ecpay:
  env: stage   # stage | prod
#  merchant-id: "3490805"     # 測試用 MerchantID（你也可換成自己後台的）
#  hash-key: "VJvftkDaKOK9hjaF"
#  hash-iv: "a514fnShdyMpnwYx"
  merchant-id: "3362787"     # ECPay 提供的測試 MerchantID
  hash-key: "5tzn8qyhl9EwzwuT"
  hash-iv: "iz8YXaAUx60tijdL"

  stage-url: "https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5"
  prod-url:  "https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5"
  public-base-url: "https://4a24-2401-e180-88e0-1a4a-1d5e-ea37-798e-80e5.ngrok-free.app"  # 換成你的 ngrok 網址

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
