server:
  port: 8085

spring:
  application:
    name: production-planning-service
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true   # 你要多事件類型就打開
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.use.type.headers: true
  datasource:
    url: jdbc:postgresql://localhost:5432/production_planning_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

app:
  kafka:
    topic:
      notification-events: batch.created.notification.v1
      threshold-reached-events: threshold.reached.v1
      batch-confirm-events: batch.confirmed.v1
    consumer:
      group-id: production-planning-service-group

services:
  order-service:
    base-url: http://localhost:8083   # local 可換成 http://localhost:8083
    timeout-ms: 3000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace