server:
  port: 8083

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: 100.113.120.124:9092
    listener:
      ack-mode: manual_immediate
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # 這樣就會在 Kafka 消息頭中添加類型信息，方便消費者反序列化
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.use.type.headers: true # 這樣就會使用 Kafka 消息頭中的類型信息來反序列化，而不是全局默認類型

  datasource:
    url: jdbc:postgresql://100.113.120.124:5432/order_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50 # 批次大小，根據實際情況調整
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_updates: true # 確保更新操作按順序執行，避免死鎖
        order_inserts: true #` 確保插入操作按順序執行，避免死鎖

  jackson:
    time-zone: UTC

app:
  kafka:
    consumer:
      group-id: order-service
    topic:
      order-reserved-events: order.reserved.v1
      sell-window-quota-configured: sell-window.quota.configured.v1
      batch-confirm-events: batch.confirmed.v1
      payment-requested-events: payment.requested.v1
      payment-completed-events: payment.completed.v1
      payment-paid-events: payment.paid.v1
  outbox:
    publish-interval-ms: 5000


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
    org.springframework.http.converter.json: debug
    org.springframework.validation: debug