server:
  port: 8087

spring:
  application:
    name: threshold-service
  kafka:
    bootstrap-servers: 100.113.120.124:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # 這樣就會在 Kafka 消息頭中添加類型信息，方便消費者反序列化
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.use.type.headers: true # 這樣就會使用 Kafka 消息頭中的類型
      group-id: order-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

  datasource:
    url: jdbc:postgresql://100.113.120.124:5432/threshold_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

app:
  kafka:
    topic:
      order-reserved-events: order.reserved.v1
      threshold-reached-events: threshold.reached.v1


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace