server:
  port: 8086

spring:
  application:
    name: production-service
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.value.default.type: "com.merdeleine.messaging.BatchCreatedNotificationEvent"
  datasource:
    url: jdbc:postgresql://localhost:5432/production_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC

app:
  kafka:
    topic:
      batch-created-notification: batch.created.notification.v1
      payment-requested: payment.requested.v1
    consumer:
      group-id: production-service-group
      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace