server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: 100.113.120.124:9092
    listener:
      ack-mode: manual_immediate
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # 這樣就會在 Kafka 消息頭中添加類型信息，方便消費者反序列化
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.merdeleine.messaging"
        spring.json.use.type.headers: true # 這樣就會使用 Kafka 消息頭中的類型信息來反序列化，而不是全局默認類型
      auto-offset-reset: earliest # 消息消費者從最早的消息開始消費，確保不會錯過任何消息
  datasource:
    url: jdbc:postgresql://100.113.120.124:5432/notification_db
    username: merdeleine
    password: merdeleine_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 你已經用 SQL 建表，建議 validate；開發期也可用 update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # 建議明確指定 dialect（Hibernate 6 通常可自動判斷，不寫也行）
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: wayne2347@gmail.com
    password: iumihqrmpvsglwls
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 50000
  jackson:
    time-zone: UTC

app:
  kafka:
    topic:
      batch-created-notification: batch.created.notification.v1
      payment-created-events: payment.created.v1
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
  mail:
    from: merdeleine.tw@gmail.com

services:
  order-service:
    base-url: http://100.113.120.124:8081
    timeout-ms: 3000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace